// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:abyadpos_tab/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhHCBwzTmr2AWfwjDXSbQw2Cnc_TW1Etg',
    appId: '1:372662509172:web:bf62146db4b74f51efbb21',
    messagingSenderId: '372662509172',
    projectId: 'abyad-pos',
    authDomain: 'abyad-pos.firebaseapp.com',
    storageBucket: 'abyad-pos.firebasestorage.app',
    measurementId: 'G-BHZQH4QFNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDU8aMCJRIBYJ66ORrVkNYZj6Sa3Xe5FQ',
    appId: '1:372662509172:android:b6d1eea77f815405efbb21',
    messagingSenderId: '372662509172',
    projectId: 'abyad-pos',
    storageBucket: 'abyad-pos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbpytskp6Nt5zdpezALSMHaJ_kg3tMrOQ',
    appId: '1:372662509172:ios:904b141be537795fefbb21',
    messagingSenderId: '372662509172',
    projectId: 'abyad-pos',
    storageBucket: 'abyad-pos.firebasestorage.app',
    iosBundleId: 'sa.abyad.laundry.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbpytskp6Nt5zdpezALSMHaJ_kg3tMrOQ',
    appId: '1:372662509172:ios:d5155f540865472fefbb21',
    messagingSenderId: '372662509172',
    projectId: 'abyad-pos',
    storageBucket: 'abyad-pos.firebasestorage.app',
    iosBundleId: 'com.ktech.abyadposTab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhHCBwzTmr2AWfwjDXSbQw2Cnc_TW1Etg',
    appId: '1:372662509172:web:ce06caef311124baefbb21',
    messagingSenderId: '372662509172',
    projectId: 'abyad-pos',
    authDomain: 'abyad-pos.firebaseapp.com',
    storageBucket: 'abyad-pos.firebasestorage.app',
    measurementId: 'G-G2R8F8N136',
  );
}